version: '3.8'
services:
  frontend:
    container_name: crm-light-frontend
    restart: unless-stopped
    image: crm-light-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment: []
    ports:
      - '3000:80'
    networks:
      - shared-network
    depends_on:
      - backend
      - keycloak
  backend:
    container_name: crm-light-backend
    restart: unless-stopped
    image: crm-light-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - KC_URL=http://keycloak:8080/auth
      - KC_ADMIN=admin
      - KC_ADMIN_PASSWORD=admin
      - KC_WEB_ORIGINS=http://localhost:3000
    networks:
      - shared-network
    depends_on:
      - keycloak
  keycloak:
    container_name: crm-light-keycloak
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - shared-network
    command:
      - start-dev
      - '--hostname'
      - localhost:3000
      - '--http-relative-path'
      - /auth
networks:
  shared-network: {}
